--[[
    Geomancer job definition
    Defines abilities, validators, and configuration for Geomancer automation
    - Geo positioning (Full Circle)
    - Pet healing (Life Cycle)
    - AOE healing (Mending Halation)
    - MP recovery (Radial Arcana)
    - Buffs (Indi and Geo spells)
]]--

local common = require('lib.core.common')

return {
    job_id = 21,  -- Geomancer
    job_name = 'Geomancer',
    resource_type = 'mp',
    
    abilities = {
        geo = {
            {
                name = 'Full Circle',
                level = 5,
                cost = 0,
                id = 243,
                command = '/ja "Full Circle" <me>',
                main_job_only = true,
                pet_required = true,
            },
            {
                name = 'Entrust',
                level = 75,
                cost = 0,
                id = 93,
                command = '/ja "Entrust" <me>',
                buff_id = 584,
                range = 20,
                combat_only = true,
                main_job_only = true,
            },
        },
        heal_pet = {
            {
                name = 'Life Cycle',
                level = 50,
                cost = 0,
                id = 246,
                command = '/ja "Life Cycle" <me>',
                combat_only = true,
                main_job_only = true,
                pet_required = true,
            },
            {
                name = 'Dematerialize',
                level = 70,
                cost = 0,
                id = 248,
                command = '/ja "Dematerialize" <me>',
                combat_only = true,
                main_job_only = true,
                pet_required = true,
            },
        },
        heal_aoe = {
            {
                name = 'Mending Halation',
                level = 75,
                cost = 0,
                id = 251,
                command = '/ja "Mending Halation" <me>',
                combat_only = true,
                main_job_only = true,
                pet_required = true,
            },
        },
        recover_mp = {
            {
                name = 'Radial Arcana',
                level = 75,
                cost = 0,
                id = 252,
                command = '/ja "Radial Arcana" <me>',
                combat_only = true,
                main_job_only = true,
                pet_required = true,
            },
        },

        -- Buffs
        buff = {
            -- Job Abilities
            {
                name = 'Lasting Emanation (Duration)',
                level = 25,
                cost = 0,
                id = 244,
                command = '/ja "Lasting Emanation" <me>',
                combat_only = true,
                main_job_only = true,
                group = 'geo_buff',
                pet_required = true,
            },
            {
                name = 'Ecliptic Attrition (Effect)',
                level = 25,
                cost = 0,
                id = 244,
                command = '/ja "Ecliptic Attrition" <me>',
                combat_only = true,
                main_job_only = true,
                group = 'geo_buff',
                pet_required = true,
            },
            {
                name = 'Blaze of Glory',
                level = 60,
                cost = 0,
                id = 247,
                command = '/ja "Blaze of Glory" <me>',
                combat_only = true,
                main_job_only = true,
            },

            -- Indi spells (highest level first)
            {
                name = 'Indi-Haste',
                level = 74,
                cost = 153,
                id = 771,
                magic = 'geomancy',
                command = '/ma "Indi-Haste" <me>',
                element = 'Wind',
                group = 'Indi',
                buff_id = 580,
            },
            {
                name = 'Indi-Frailty',
                level = 74,
                cost = 159,
                id = 788,
                magic = 'geomancy',
                command = '/ma "Indi-Frailty" <me>',
                element = 'Wind',
                group = 'Indi',
                buff_id = 564,
            },
            {
                name = 'Indi-Vex',
                level = 70,
                cost = 144,
                id = 793,
                magic = 'geomancy',
                command = '/ma "Indi-Vex" <me>',
                element = 'Light',
                group = 'Indi',
                buff_id = 563,
            },
            {
                name = 'Indi-Paralysis',
                level = 68,
                cost = 138,
                id = 796,
                magic = 'geomancy',
                command = '/ma "Indi-Paralysis" <me>',
                element = 'Ice',
                group = 'Indi',
                buff_id = 566,
            },
            {
                name = 'Indi-Languor',
                level = 64,
                cost = 135,
                id = 794,
                magic = 'geomancy',
                command = '/ma "Indi-Languor" <me>',
                element = 'Dark',
                group = 'Indi',
                buff_id = 559,
            },
            {
                name = 'Indi-Slip',
                level = 58,
                cost = 129,
                id = 791,
                magic = 'geomancy',
                command = '/ma "Indi-Slip" <me>',
                element = 'Earth',
                group = 'Indi',
                buff_id = 561,
            },
            {
                name = 'Indi-Torpor',
                level = 52,
                cost = 114,
                id = 792,
                magic = 'geomancy',
                command = '/ma "Indi-Torpor" <me>',
                element = 'Ice',
                group = 'Indi',
                buff_id = 562,
            },
            {
                name = 'Indi-STR',
                level = 48,
                cost = 102,
                id = 772,
                magic = 'geomancy',
                command = '/ma "Indi-STR" <me>',
                element = 'Fire',
                group = 'Indi',
                buff_id = 542,
            },
            {
                name = 'Indi-Slow',
                level = 48,
                cost = 105,
                id = 795,
                magic = 'geomancy',
                command = '/ma "Indi-Slow" <me>',
                element = 'Earth',
                group = 'Indi',
                buff_id = 565,
            },
            {
                name = 'Indi-Acumen',
                level = 46,
                cost = 96,
                id = 781,
                magic = 'geomancy',
                command = '/ma "Indi-Acumen" <me>',
                element = 'Ice',
                group = 'Indi',
                buff_id = 551,
            },
            {
                name = 'Indi-DEX',
                level = 45,
                cost = 93,
                id = 773,
                magic = 'geomancy',
                command = '/ma "Indi-DEX" <me>',
                element = 'Thunder',
                group = 'Indi',
                buff_id = 543,
            },
            {
                name = 'Indi-VIT',
                level = 42,
                cost = 84,
                id = 774,
                magic = 'geomancy',
                command = '/ma "Indi-VIT" <me>',
                element = 'Earth',
                group = 'Indi',
                buff_id = 544,
            },
            {
                name = 'Indi-Fend',
                level = 40,
                cost = 78,
                id = 782,
                magic = 'geomancy',
                command = '/ma "Indi-Fend" <me>',
                element = 'Water',
                group = 'Indi',
                buff_id = 550,
            },
            {
                name = 'Indi-AGI',
                level = 39,
                cost = 75,
                id = 775,
                magic = 'geomancy',
                command = '/ma "Indi-AGI" <me>',
                element = 'Wind',
                group = 'Indi',
                buff_id = 545,
            },
            {
                name = 'Indi-INT',
                level = 36,
                cost = 66,
                id = 776,
                magic = 'geomancy',
                command = '/ma "Indi-INT" <me>',
                element = 'Ice',
                group = 'Indi',
                buff_id = 546,
            },
            {
                name = 'Indi-Fury',
                level = 34,
                cost = 57,
                id = 779,
                magic = 'geomancy',
                command = '/ma "Indi-Fury" <me>',
                element = 'Fire',
                group = 'Indi',
                buff_id = 549,
            },
            {
                name = 'Indi-MND',
                level = 33,
                cost = 54,
                id = 777,
                magic = 'geomancy',
                command = '/ma "Indi-MND" <me>',
                element = 'Water',
                group = 'Indi',
                buff_id = 547,
            },
            {
                name = 'Indi-Refresh',
                level = 30,
                cost = 63,
                id = 770,
                magic = 'geomancy',
                command = '/ma "Indi-Refresh" <me>',
                element = 'Light',
                group = 'Indi',
                buff_id = 541,
            },
            {
                name = 'Indi-Barrier',
                level = 28,
                cost = 48,
                id = 780,
                magic = 'geomancy',
                command = '/ma "Indi-Barrier" <me>',
                element = 'Earth',
                group = 'Indi',
                buff_id = 552,
            },
            {
                name = 'Indi-Focus',
                level = 22,
                cost = 42,
                id = 785,
                magic = 'geomancy',
                command = '/ma "Indi-Focus" <me>',
                element = 'Dark',
                group = 'Indi',
                buff_id = 553,
            },
            {
                name = 'Indi-Attunement',
                level = 16,
                cost = 33,
                id = 786,
                magic = 'geomancy',
                command = '/ma "Indi-Attunement" <me>',
                element = 'Light',
                group = 'Indi',
                buff_id = 556,
            },
            {
                name = 'Indi-Regen',
                level = 15,
                cost = 30,
                id = 768,
                magic = 'geomancy',
                command = '/ma "Indi-Regen" <me>',
                element = 'Light',
                group = 'Indi',
                buff_id = 539,
            },
            {
                name = 'Indi-Precision',
                level = 10,
                cost = 24,
                id = 783,
                magic = 'geomancy',
                command = '/ma "Indi-Precision" <me>',
                element = 'Thunder',
                group = 'Indi',
                buff_id = 553,
            },
            {
                name = 'Indi-Voidance',
                level = 4,
                cost = 15,
                id = 784,
                magic = 'geomancy',
                command = '/ma "Indi-Voidance" <me>',
                element = 'Wind',
                group = 'Indi',
                buff_id = 554,
            },
            {
                name = 'Indi-Poison',
                level = 1,
                cost = 12,
                id = 769,
                magic = 'geomancy',
                command = '/ma "Indi-Poison" <me>',
                element = 'Water',
                group = 'Indi',
                buff_id = 540,
            },
            -- Geo spells (highest level first)
            {
                name = 'Geo-Vex',
                level = 74,
                cost = 150,
                id = 823,
                magic = 'geomancy',
                command = '/ma "Geo-Vex" <bt>',
                element = 'Light',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 563,
            },
            {
                name = 'Geo-Haste',
                level = 74,
                cost = 156,
                id = 801,
                magic = 'geomancy',
                command = '/ma "Geo-Haste" <me>',
                element = 'Wind',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 580,
            },
            {
                name = 'Geo-Frailty',
                level = 74,
                cost = 162,
                id = 818,
                magic = 'geomancy',
                command = '/ma "Geo-Frailty" <bt>',
                element = 'Wind',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 564,
            },
            {
                name = 'Geo-Paralysis',
                level = 72,
                cost = 147,
                id = 826,
                magic = 'geomancy',
                command = '/ma "Geo-Paralysis" <bt>',
                element = 'Ice',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 566,
            },
            {
                name = 'Geo-Languor',
                level = 68,
                cost = 141,
                id = 824,
                magic = 'geomancy',
                command = '/ma "Geo-Languor" <bt>',
                element = 'Dark',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 559,
            },
            {
                name = 'Geo-Slip',
                level = 62,
                cost = 132,
                id = 821,
                magic = 'geomancy',
                command = '/ma "Geo-Slip" <bt>',
                element = 'Earth',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 561,
            },
            {
                name = 'Geo-Torpor',
                level = 56,
                cost = 126,
                id = 822,
                magic = 'geomancy',
                command = '/ma "Geo-Torpor" <bt>',
                element = 'Ice',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 562,
            },
            {
                name = 'Geo-STR',
                level = 52,
                cost = 117,
                id = 802,
                magic = 'geomancy',
                command = '/ma "Geo-STR" <me>',
                element = 'Fire',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 542,
            },
            {
                name = 'Geo-Slow',
                level = 52,
                cost = 120,
                id = 825,
                magic = 'geomancy',
                command = '/ma "Geo-Slow" <bt>',
                element = 'Earth',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 565,
            },
            {
                name = 'Geo-Acumen',
                level = 50,
                cost = 111,
                id = 811,
                magic = 'geomancy',
                command = '/ma "Geo-Acumen" <me>',
                element = 'Ice',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 551,
            },
            {
                name = 'Geo-DEX',
                level = 49,
                cost = 108,
                id = 803,
                magic = 'geomancy',
                command = '/ma "Geo-DEX" <me>',
                element = 'Thunder',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 543,
            },
            {
                name = 'Geo-VIT',
                level = 46,
                cost = 99,
                id = 804,
                magic = 'geomancy',
                command = '/ma "Geo-VIT" <me>',
                element = 'Earth',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 544,
            },
            {
                name = 'Geo-Fend',
                level = 44,
                cost = 90,
                id = 812,
                magic = 'geomancy',
                command = '/ma "Geo-Fend" <me>',
                element = 'Water',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 550,
            },
            {
                name = 'Geo-AGI',
                level = 43,
                cost = 87,
                id = 805,
                magic = 'geomancy',
                command = '/ma "Geo-AGI" <me>',
                element = 'Wind',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 545,
            },
            {
                name = 'Geo-INT',
                level = 40,
                cost = 81,
                id = 806,
                magic = 'geomancy',
                command = '/ma "Geo-INT" <me>',
                element = 'Ice',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 546,
            },
            {
                name = 'Geo-Fury',
                level = 38,
                cost = 72,
                id = 809,
                magic = 'geomancy',
                command = '/ma "Geo-Fury" <me>',
                element = 'Fire',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 549,
            },
            {
                name = 'Geo-MND',
                level = 37,
                cost = 69,
                id = 807,
                magic = 'geomancy',
                command = '/ma "Geo-MND" <me>',
                element = 'Water',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 547,
            },
            {
                name = 'Geo-Refresh',
                level = 34,
                cost = 60,
                id = 800,
                magic = 'geomancy',
                command = '/ma "Geo-Refresh" <me>',
                element = 'Light',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 541,
            },
            {
                name = 'Geo-CHR',
                level = 34,
                cost = 63,
                id = 808,
                magic = 'geomancy',
                command = '/ma "Geo-CHR" <me>',
                element = 'Light',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 548,
            },
            {
                name = 'Geo-Barrier',
                level = 32,
                cost = 51,
                id = 810,
                magic = 'geomancy',
                command = '/ma "Geo-Barrier" <me>',
                element = 'Earth',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 552,
            },
            {
                name = 'Geo-Focus',
                level = 26,
                cost = 45,
                id = 815,
                magic = 'geomancy',
                command = '/ma "Geo-Focus" <me>',
                element = 'Dark',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 553,
            },
            {
                name = 'Geo-Attunement',
                level = 20,
                cost = 39,
                id = 816,
                magic = 'geomancy',
                command = '/ma "Geo-Attunement" <me>',
                element = 'Light',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 556,
            },
            {
                name = 'Geo-Regen',
                level = 19,
                cost = 36,
                id = 798,
                magic = 'geomancy',
                command = '/ma "Geo-Regen" <me>',
                element = 'Light',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 539,
            },
            {
                name = 'Geo-Precision',
                level = 14,
                cost = 27,
                id = 813,
                magic = 'geomancy',
                command = '/ma "Geo-Precision" <me>',
                element = 'Thunder',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 553,
            },
            {
                name = 'Geo-Voidance',
                level = 8,
                cost = 21,
                id = 814,
                magic = 'geomancy',
                command = '/ma "Geo-Voidance" <me>',
                element = 'Wind',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 554,
            },
            {
                name = 'Geo-Poison',
                level = 5,
                cost = 18,
                id = 799,
                magic = 'geomancy',
                command = '/ma "Geo-Poison" <bt>',
                element = 'Water',
                group = 'Geo',
                main_job_only = true,
                combat_only = true,
                buff_id = 540,
            },
        },
    },
    
    -- Default settings for UI
    default_settings = {
        heal_enabled = true,
        heal_threshold = 75,
        heal_aoe_enabled = true,
        heal_aoe_threshold = 70,
        heal_aoe_count_threshold = 2,
        wake_enabled = false,
        buff_enabled = true,
        debuff_removal_enabled = false,
        heal_pet_enabled = true,
        geo_enabled = true,
        geo_distance_threshold = 10,
        rest_enabled = false,
        rest_timer = 5,
        rest_threshold = 70,
        rest_distance = 7,
    },
    
    -- Action priority order
    priority_order = {
        'item',
        'recover',
        'heal_aoe',
        'heal_pet',
        'heal',
        'buff',
        'geo',
        'rest',
    },
}