--[[
    Red Mage job definition
    Defines abilities, validators, and configuration for Red Mage automation
    - Healing (Cure spells)
    - Buffs (Haste, Refresh, Regen, Protect, Shell, Phalanx, Aquaveil, Blink, Stoneskin, Enspells)
    - MP recovery (Convert)
]]--


return {
    job_id = 5,
    job_name = 'Red Mage',
    resource_type = 'mp',
    
    abilities = {
        -- Single-target healing
        heal = {
            {
                name = 'Cure IV',
                level = 48,
                cost = 88,
                spell_id = 4,
                magic = 'white',
                magic_type = 'healing',
                command = function(target)
                    return '/ma "Cure IV" '..target
                end,
                range = 20,
                value = 400,
                wakes = true,
                target_outside = true,
            },
            {
                name = 'Cure III',
                level = 26,
                cost = 46,
                spell_id = 3,
                magic = 'white',
                magic_type = 'healing',
                command = function(target)
                    return '/ma "Cure III" '..target
                end,
                range = 20,
                value = 200,
                wakes = true,
                target_outside = true,
            },
            {
                name = 'Cure II',
                level = 14,
                cost = 24,
                spell_id = 2,
                magic = 'white',
                magic_type = 'healing',
                command = function(target)
                    return '/ma "Cure II" '..target
                end,
                range = 20,
                value = 90,
                wakes = true,
                target_outside = true,
            },
            {
                name = 'Cure',
                level = 3,
                cost = 8,
                spell_id = 1,
                magic = 'white',
                magic_type = 'healing',
                command = function(target)
                    return '/ma "Cure" '..target
                end,
                range = 20,
                value = 30,
                wakes = true,
                target_outside = true,
            },
        },
        
        -- Buffs (Enhancing magic)
        buff = {
            -- Job Abilities
            {
                name = 'Composure',
                level = 50,
                cost = 0,
                recast_id = 50,
                command = '/ja "Composure" <me>',
                buff_id = 419,
                priority = 100,
            },
            -- Protect line
            {
                name = 'Protect IV',
                level = 63,
                cost = 65,
                spell_id = 46,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Protect IV" '..target
                end,
                buff_id = 40,
                group = 'protect',
                target_outside = true,
            },
            {
                name = 'Protect III',
                level = 47,
                cost = 46,
                spell_id = 45,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Protect III" '..target
                end,
                buff_id = 40,
                group = 'protect',
                target_outside = true,
            },
            {
                name = 'Protect II',
                level = 27,
                cost = 28,
                spell_id = 44,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Protect II" '..target
                end,
                buff_id = 40,
                group = 'protect',
                target_outside = true,
            },
            {
                name = 'Protect',
                level = 7,
                cost = 9,
                spell_id = 43,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Protect" '..target
                end,
                buff_id = 40,
                group = 'protect',
                target_outside = true,
            },
            -- Shell line
            {
                name = 'Shell IV',
                level = 68,
                cost = 75,
                spell_id = 51,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Shell IV" '..target
                end,
                buff_id = 41,
                group = 'shell',
                target_outside = true,
            },
            {
                name = 'Shell III',
                level = 57,
                cost = 56,
                spell_id = 50,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Shell III" '..target
                end,
                buff_id = 41,
                group = 'shell',
                target_outside = true,
            },
            {
                name = 'Shell II',
                level = 37,
                cost = 37,
                spell_id = 49,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Shell II" '..target
                end,
                buff_id = 41,
                group = 'shell',
                target_outside = true,
            },
            {
                name = 'Shell',
                level = 17,
                cost = 18,
                spell_id = 48,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Shell" '..target
                end,
                buff_id = 41,
                group = 'shell',
                target_outside = true,
            },
            -- Barelement
            {
                name = 'Barstone',
                level = 5,
                cost = 6,
                spell_id = 63,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barstone" <me>',
                element = 'Wind',
                buff_id = 103,
                group = 'barelement',
            },
            {
                name = 'Barwater',
                level = 9,
                cost = 6,
                spell_id = 65,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barwater" <me>',
                element = 'Thunder',
                buff_id = 105,
                group = 'barelement',
            },
            {
                name = 'Baraero',
                level = 13,
                cost = 6,
                spell_id = 62,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Baraero" <me>',
                element = 'Ice',
                buff_id = 102,
                group = 'barelement',
            },
            {
                name = 'Barfire',
                level = 17,
                cost = 6,
                spell_id = 60,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barfire" <me>',
                element = 'Water',
                buff_id = 100,
                group = 'barelement',
            },
            {
                name = 'Barblizzard',
                level = 21,
                cost = 6,
                spell_id = 61,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barblizzard" <me>',
                element = 'Fire',
                buff_id = 101,
                group = 'barelement',
            },
            {
                name = 'Barthunder',
                level = 25,
                cost = 6,
                spell_id = 64,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barthunder" <me>',
                element = 'Earth',
                buff_id = 104,
                group = 'barelement',
            },
            -- Barstatus
            {
                name = 'Barsleep',
                level = 7,
                cost = 7,
                spell_id = 72,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barsleep" <me>',
                element = 'Light',
                buff_id = 106,
                group = 'barstatus',
            },
            {
                name = 'Barpoison',
                level = 10,
                cost = 9,
                spell_id = 73,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barpoison" <me>',
                element = 'Thunder',
                buff_id = 107,
                group = 'barstatus',
            },
            {
                name = 'Barparalyze',
                level = 12,
                cost = 11,
                spell_id = 74,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barparalyze" <me>',
                element = 'Fire',
                buff_id = 108,
                group = 'barstatus',
            },
            {
                name = 'Barblind',
                level = 18,
                cost = 13,
                spell_id = 75,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barblind" <me>',
                element = 'Light',
                buff_id = 109,
                group = 'barstatus',
            },
            {
                name = 'Barsilence',
                level = 23,
                cost = 15,
                spell_id = 76,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barsilence" <me>',
                element = 'Ice',
                buff_id = 110,
                group = 'barstatus',
            },
            {
                name = 'Barvirus',
                level = 39,
                cost = 25,
                spell_id = 78,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barvirus" <me>',
                element = 'Water',
                buff_id = 112,
                group = 'barstatus',
            },
            {
                name = 'Barpetrify',
                level = 43,
                cost = 20,
                spell_id = 77,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Barpetrify" <me>',
                element = 'Wind',
                buff_id = 111,
                group = 'barstatus',
            },
            {
                name = 'Baramnesia',
                level = 65,
                cost = 30,
                spell_id = 84,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Baramnesia" <me>',
                element = 'Water',
                buff_id = 286,
                group = 'barstatus',
            },
            -- Other buffs
            {
                name = 'Phalanx II',
                level = 75,
                cost = 42,
                spell_id = 107,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Phalanx II" '..target
                end,
                buff_id = 116,
            },
            {
                name = 'Regen',
                level = 21,
                cost = 15,
                spell_id = 108,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Regen" '..target
                end,
                buff_id = 42,
            },
            {
                name = 'Refresh',
                level = 41,
                cost = 40,
                spell_id = 109,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Refresh" '..target
                end,
                buff_id = 43,
                priority = 50,
            },
            {
                name = 'Haste',
                level = 48,
                cost = 40,
                spell_id = 57,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Haste" '..target
                end,
                buff_id = 33,
                target_outside = true,
            },
            {
                name = 'Flurry',
                level = 48,
                cost = 40,
                spell_id = 845,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Flurry" '..target
                end,
                buff_id = 265,
                target_outside = true,
            },
            {
                name = 'Stoneskin',
                level = 34,
                cost = 29,
                spell_id = 54,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Stoneskin" <me>',
                buff_id = 37,
            },
            {
                name = 'Phalanx',
                level = 33,
                cost = 21,
                spell_id = 106,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Phalanx" <me>',
                buff_id = 116,
            },
            {
                name = 'Blink',
                level = 23,
                cost = 20,
                spell_id = 53,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Blink" <me>',
                buff_id = 36,
            },
            {
                name = 'Aquaveil',
                level = 12,
                cost = 12,
                spell_id = 55,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Aquaveil" <me>',
                buff_id = 39,
            },
            -- Enspells (grouped by element)
            {
                name = 'Enwater II',
                level = 60,
                cost = 24,
                spell_id = 317,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enwater II" <me>',
                buff_id = 282,
                group = 'enspell',
            },
            {
                name = 'Enwater',
                level = 27,
                cost = 12,
                spell_id = 105,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enwater" <me>',
                buff_id = 99,
                group = 'enspell',
            },
            {
                name = 'Enfire II',
                level = 58,
                cost = 24,
                spell_id = 312,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enfire II" <me>',
                buff_id = 277,
                group = 'enspell',
            },
            {
                name = 'Enfire',
                level = 24,
                cost = 12,
                spell_id = 100,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enfire" <me>',
                buff_id = 94,
                group = 'enspell',
            },
            {
                name = 'Enblizzard II',
                level = 56,
                cost = 24,
                spell_id = 313,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enblizzard II" <me>',
                buff_id = 278,
                group = 'enspell',
            },
            {
                name = 'Enblizzard',
                level = 22,
                cost = 12,
                spell_id = 101,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enblizzard" <me>',
                buff_id = 95,
                group = 'enspell',
            },
            {
                name = 'Enaero II',
                level = 54,
                cost = 24,
                spell_id = 314,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enaero II" <me>',
                buff_id = 279,
                group = 'enspell',
            },
            {
                name = 'Enaero',
                level = 20,
                cost = 12,
                spell_id = 102,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enaero" <me>',
                buff_id = 96,
                group = 'enspell',
            },
            {
                name = 'Enstone II',
                level = 52,
                cost = 24,
                spell_id = 315,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enstone II" <me>',
                buff_id = 280,
                group = 'enspell',
            },
            {
                name = 'Enstone',
                level = 18,
                cost = 12,
                spell_id = 103,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enstone" <me>',
                buff_id = 97,
                group = 'enspell',
            },
            {
                name = 'Enthunder II',
                level = 50,
                cost = 24,
                spell_id = 316,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enthunder II" <me>',
                buff_id = 281,
                group = 'enspell',
            },
            {
                name = 'Enthunder',
                level = 16,
                cost = 12,
                spell_id = 104,
                magic = 'white',
                magic_type = 'enhancing',
                command = '/ma "Enthunder" <me>',
                buff_id = 98,
                group = 'enspell',
            },
            -- Spikes (sorted by level, highest first)
            {
                name = 'Shock Spikes',
                level = 60,
                cost = 24,
                spell_id = 251,
                magic = 'black',
                magic_type = 'enhancing',
                command = '/ma "Shock Spikes" <me>',
                buff_id = 38,
                group = 'spikes'
            },
            {
                name = 'Ice Spikes',
                level = 40,
                cost = 16,
                spell_id = 250,
                magic = 'black',
                magic_type = 'enhancing',
                command = '/ma "Ice Spikes" <me>',
                buff_id = 35,
                group = 'spikes'
            },
            {
                name = 'Blaze Spikes',
                level = 20,
                cost = 8,
                spell_id = 249,
                magic = 'black',
                magic_type = 'enhancing',
                command = '/ma "Blaze Spikes" <me>',
                buff_id = 34,
                group = 'spikes'
            },
            {
                name = 'Invisible',
                level = 25,
                cost = 15,
                spell_id = 136,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Invisible" '..target
                end,
                buff_id = 69,
                idle_only = true,
            },
            {
                name = 'Sneak',
                level = 20,
                cost = 12,
                spell_id = 137,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Sneak" '..target
                end,
                buff_id = 71,
                idle_only = true,
            },
            {
                name = 'Deodorize',
                level = 15,
                cost = 10,
                spell_id = 138,
                magic = 'white',
                magic_type = 'enhancing',
                command = function(target)
                    return '/ma "Deodorize" '..target
                end,
                idle_only = true,
                buff_id = 70,
            },
        },

        -- Recover MP
        recover_mp = {
            {
                name = 'Convert',
                level = 40,
                cost = 0,
                recast_id = 49,  -- Job ability
                command = '/ja "Convert" <me>',
            },
        },

        -- Revive
        revive = {
            {
                name = 'Raise',
                level = 38,
                cost = 150,
                spell_id = 12,
                command = function(target)
                    return '/ma "Raise" '..target
                end,
                range = 18,
                magic_type = 'healing',
                idle_only = true,
                target_outside = true,
            },
        },
    },
    
    -- Default settings for UI
    default_settings = {
        heal_enabled = true,
        heal_threshold = 75,
        wake_enabled = true,
        buff_enabled = true,
        recover_enabled = true,
        recover_mp_threshold = 20,  -- Use Convert when MP drops below 20%
        focus_enabled = false,
        focus_threshold = 85,
        revive_enabled = true,
    },
    
    -- Action priority order
    priority_order = {
        'item',
        'recover',
        'heal',
        'wake',
        'revive',
        'buff',
        'rest',
    },
}
